
#pragma once

/*
 * This file was generated by 'metaprogram.cpp'. It contains information about
 * various datastructures to be able to use introspection
*/

#include "base.h"

enum MetaType
{
    Meta_Unknown = 0,
    Meta_Int,
    Meta_Float,
    Meta_Vec3,
};

struct MetaTypeInfo
{
    MetaType metaType;
    int numPointers;
    bool isSlice;
    bool isString;
};

struct MemberDefinition
{
    MetaTypeInfo typeInfo;
    int offset;
    String name;
    const char* cName;
};

MemberDefinition membersOfEntity[] =
{
{ { Meta_Vec3, 0, false, false }, offsetof(Entity, pos), StrLit("pos"), "pos" },
{ { Meta_Unknown, 0, false, false }, offsetof(Entity, rot), StrLit("rot"), "rot" },
{ { Meta_Vec3, 0, false, false }, offsetof(Entity, scale), StrLit("scale"), "scale" },
{ { Meta_Unknown, 0, false, false }, offsetof(Entity, flags), StrLit("flags"), "flags" },
{ { Meta_Unknown, 0, false, false }, offsetof(Entity, gen), StrLit("gen"), "gen" },
{ { Meta_Unknown, 0, false, false }, offsetof(Entity, derivedKind), StrLit("derivedKind"), "derivedKind" },
{ { Meta_Unknown, 0, false, false }, offsetof(Entity, derivedId), StrLit("derivedId"), "derivedId" },
{ { Meta_Unknown, 0, false, false }, offsetof(Entity, model), StrLit("model"), "model" },
{ { Meta_Unknown, 0, false, false }, offsetof(Entity, mount), StrLit("mount"), "mount" },
{ { Meta_Unknown, 0, false, false }, offsetof(Entity, mountBone), StrLit("mountBone"), "mountBone" },
};

MemberDefinition membersOfCamera[] =
{
{ { Meta_Unknown, 0, false, false }, offsetof(Camera, base), StrLit("base"), "base" },
{ { Meta_Float, 0, false, false }, offsetof(Camera, horizontalFOV), StrLit("horizontalFOV"), "horizontalFOV" },
{ { Meta_Float, 0, false, false }, offsetof(Camera, nearClip), StrLit("nearClip"), "nearClip" },
{ { Meta_Float, 0, false, false }, offsetof(Camera, farClip), StrLit("farClip"), "farClip" },
};

MemberDefinition membersOfPlayer[] =
{
{ { Meta_Unknown, 0, false, false }, offsetof(Player, base), StrLit("base"), "base" },
{ { Meta_Vec3, 0, false, false }, offsetof(Player, speed), StrLit("speed"), "speed" },
{ { Meta_Unknown, 0, false, false }, offsetof(Player, grounded), StrLit("grounded"), "grounded" },
};

MemberDefinition membersOfPointLight[] =
{
{ { Meta_Unknown, 0, false, false }, offsetof(PointLight, base), StrLit("base"), "base" },
{ { Meta_Float, 0, false, false }, offsetof(PointLight, intensity), StrLit("intensity"), "intensity" },
{ { Meta_Vec3, 0, false, false }, offsetof(PointLight, offset), StrLit("offset"), "offset" },
};

template<typename t>
Slice<MemberDefinition> MembersOf()
{
    if constexpr (std::is_same_v<Entity, t>)
    {
        return {.ptr=membersOfEntity, .len=ArrayCount(membersOfEntity)};
    }
    else if constexpr (std::is_same_v<Camera, t>)
    {
        return {.ptr=membersOfCamera, .len=ArrayCount(membersOfCamera)};
    }
    else if constexpr (std::is_same_v<Player, t>)
    {
        return {.ptr=membersOfPlayer, .len=ArrayCount(membersOfPlayer)};
    }
    else if constexpr (std::is_same_v<PointLight, t>)
    {
        return {.ptr=membersOfPointLight, .len=ArrayCount(membersOfPointLight)};
    }
    else
        static_assert(false, "Given type is not being introspected (add introspect keyword)");
};
